FROM rust:1.66 as builder
WORKDIR /usr/local
COPY . .
RUN cargo install --path=./ --features=standalone --bins \
    && cargo clean

FROM rust:latest
WORKDIR /
COPY --from=builder /usr/local/cargo/bin/solana-snapshot-fork /usr/local/bin/solana-snapshot-fork
CMD ["solana-snapshot-fork", "/data/snapshot_downloaded1.tar.zst", "--sqlite-out", "/data/snapshot.db"]